CssSyntaxError: postcss-nesting `@nest` was removed from the CSS Nesting specification and will be removed from PostCSS Nesting in the next major version. Manually removing '@nest ' from all PCSS files