Remove native typehints
Since they cannot be used

TypeError: Drupal\Core\Access\AccessResult::andAllowedIf(): Return value must be of type Drupal\Core\Access\AccessResultAllowed, Drupal\Core\Access\AccessResultNeutral returned core/lib/Drupal/Core/Access/AccessResult.php:137